# Prometheus Configuration for Pro-Forma Analytics Tool
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'proforma-monitor'
    environment: 'production'

rule_files:
  - "/etc/prometheus/alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Pro-Forma Analytics API
  - job_name: 'proforma-api'
    static_configs:
      - targets: ['proforma-api:8000']
    scrape_interval: 15s
    metrics_path: /api/v1/metrics
    params:
      format: ['prometheus']
    basic_auth:
      username: 'monitoring'
      password: 'monitoring123'  # Change in production
    scrape_timeout: 10s
    honor_labels: true

  # System metrics (if node_exporter is deployed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    honor_labels: true

  # Redis metrics (if redis_exporter is deployed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    honor_labels: true

  # PostgreSQL metrics (if postgres_exporter is deployed)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    honor_labels: true

  # Nginx metrics (if nginx-prometheus-exporter is deployed)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    honor_labels: true

  # Application health checks
  - job_name: 'proforma-health'
    static_configs:
      - targets: ['proforma-api:8000']
    scrape_interval: 30s
    metrics_path: /api/v1/health
    scrape_timeout: 5s