var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/analysis/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__78d85c2e._.js")
R.c("server/chunks/ssr/_a3b9117b._.js")
R.c("server/chunks/ssr/_7bf55044._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1257d2b0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fefa2633._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8bc915f6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_(dashboard)_layout_tsx_63e7d447._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_analysis_page_actions_47140bc3.js")
R.m(9996)
module.exports=R.m(9996).exports
